module.exports = {
    SESSION_ID: "SUBZERO-MD;;;XMdEEQ6C#1Nffa4t4FR_fVzUEjoyLyAmHO3l0C6H1WqeJ_RArg6M", // PUT SESSION ID HERE
    OWNER_NUMBER: "2637", // PUT OWNER NUMBER HERE
    PREFIX: "!" // DEFAULT PREFIX
};