module.exports = {
  SESSION_ID: "SUBZERO-MD;;;7IdmFLYA#_cfusRig3Q0SazLwuQ9n62JboqeCpaBYXcjclJ3aARQ", // PUT SESSION ID HERE 
  OWNER_NUMBER: "263719647303", // PUT OWNER NUMBER HERE
  PREFIX: "." // DEFAULT PREFIX
};
